FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Licencia

Polls is a simple API allowing consumers to view polls and vote in them.

## Puntos [/api/licencia/puntos/consultar]

### Consultar [POST]

+ Attributes
    + tipo_documento (required, string) - Tipo de documento.
    + numero_documento (required, string) - Número de DNI del postulante.

+ Request (application/json)

    + Body

            {
                "tipo_documento": "2",
                "numero_documento": "41424344"
            }

+ Response 200 (application/json)

        [
            {
                "apellidos_nombres": "Diaz Reyex Secmar",
                "numero_licencia": "Q45215215",
                "clase_categoria": "02/02/2018",
                "estado_licencia": "Vigente",
                "faltas_muygraves":"1",
                "faltas_graves":"3".
                "puntos_firmes":"20"
            }
        ]

## Record [/api/licencia/Record/consultar]

### Consultar [POST]

+ Attributes
    + tipo_documento (required, string) - Tipo de documento.
    + numero_documento (required, string) - Número de DNI del postulante.
    + correo (optional, string) - correo.
    
    
+ Request (application/json)

    + Body

            {
                "tipo_documento": "2",
                "numero_documento": "41424344",
                "correo":"prueba@mtc.gob.pe"
            }

+ Response 200 (application/json)

    + Body

            {
                "documento": "base64:zxcsaczxczxcsacsdcdsfsdfsdxczczxcsdczxczxczxc",
            }